// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProiectDAW.data;

#nullable disable

namespace ProiectDAW.Migrations
{
    [DbContext(typeof(ProiectDAWcontext))]
    [Migration("20220506083516_Update3")]
    partial class Update3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ProiectDAW.Models.adreseAngajati", b =>
                {
                    b.Property<int>("IdAdresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAdresa"), 1L, 1);

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdAngajat")
                        .HasColumnType("int");

                    b.Property<string>("Oras")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tara")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdAdresa");

                    b.ToTable("adreseAngajatis");
                });

            modelBuilder.Entity("ProiectDAW.Models.departamente", b =>
                {
                    b.Property<int>("IdDepartament")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDepartament"), 1L, 1);

                    b.Property<string>("NumeDepartament")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdDepartament");

                    b.ToTable("departamentes");
                });

            modelBuilder.Entity("ProiectDAW.Models.detaliiAngajati", b =>
                {
                    b.Property<int>("IdAngajat")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdDepartament")
                        .HasColumnType("int");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParolaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Salariu")
                        .HasColumnType("int");

                    b.HasKey("IdAngajat");

                    b.HasIndex("IdDepartament");

                    b.ToTable("detaliiAngajatis");
                });

            modelBuilder.Entity("ProiectDAW.Models.proiecte", b =>
                {
                    b.Property<int>("IdProiect")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProiect"), 1L, 1);

                    b.Property<string>("DetaliiProiect")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdProiect");

                    b.ToTable("proiectes");
                });

            modelBuilder.Entity("ProiectDAW.Models.proiecteAngajati", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("IdAngajat")
                        .HasColumnType("int");

                    b.Property<int>("IdProiect")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("IdAngajat");

                    b.HasIndex("IdProiect");

                    b.ToTable("proiecteAngajatis");
                });

            modelBuilder.Entity("ProiectDAW.Models.detaliiAngajati", b =>
                {
                    b.HasOne("ProiectDAW.Models.adreseAngajati", "Adresa")
                        .WithOne("Angajati")
                        .HasForeignKey("ProiectDAW.Models.detaliiAngajati", "IdAngajat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProiectDAW.Models.departamente", "Departamente")
                        .WithMany("Angajati")
                        .HasForeignKey("IdDepartament")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Adresa");

                    b.Navigation("Departamente");
                });

            modelBuilder.Entity("ProiectDAW.Models.proiecteAngajati", b =>
                {
                    b.HasOne("ProiectDAW.Models.detaliiAngajati", "detaliiAngajati")
                        .WithMany("proiecteAngajati")
                        .HasForeignKey("IdAngajat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProiectDAW.Models.proiecte", "proiecte")
                        .WithMany("proiecteAngajati")
                        .HasForeignKey("IdProiect")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("detaliiAngajati");

                    b.Navigation("proiecte");
                });

            modelBuilder.Entity("ProiectDAW.Models.adreseAngajati", b =>
                {
                    b.Navigation("Angajati")
                        .IsRequired();
                });

            modelBuilder.Entity("ProiectDAW.Models.departamente", b =>
                {
                    b.Navigation("Angajati");
                });

            modelBuilder.Entity("ProiectDAW.Models.detaliiAngajati", b =>
                {
                    b.Navigation("proiecteAngajati");
                });

            modelBuilder.Entity("ProiectDAW.Models.proiecte", b =>
                {
                    b.Navigation("proiecteAngajati");
                });
#pragma warning restore 612, 618
        }
    }
}
